# Willy Linux - pacman configuration
# Optimized for lightweight system

[options]
Color
CheckSpace
VerbosePkgLists
ILoveCandy
ParallelDownloads = 5

# Repositorios oficiales de Arch
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Repositorio comunitario (si es necesario)
[community]
Include = /etc/pacman.d/mirrorlist
